language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - echo "my favorite food is $NAME"

script:
  - docker --version # print the version for logging
  - docker build -t simple-node  --build-arg NAME=${NAME} .
  - docker tag simple-node geedino07/simple-node:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push geedino07/simple-node:v2

  